### ISSUE TITLE
Support for CUDA version 11.x

### ISSUE THREAD

**Issue by HJoonKwon** [Tangshitao/QuadTreeAttention#11]
I appreciate your great work and thank you for releasing it as opensource. 

I guess the current compiling option with setup.py only works with CUDA version 10.2. 
Are you guys planning to support CUDA 11.x as well? 
Some gpus like rtx 30 series do not support CUDA 10.x, which is quite annoying.. 

Thank you for your attention :)

**Comment by Tangshitao** [comment]
I can compile the codes without any problems on CUDA 11. Do you have any error messages?

**Comment by HJoonKwon** [comment]
@Tangshitao  Sorry for bothering you. It was a cuda-version mismatch problem on local server. Thank you. :)
