### ISSUE TITLE
How to train the model for MegaDepth Dataset

### ISSUE THREAD

**Issue by xmlyqing00** [Tangshitao/QuadTreeAttention#30]
Hi,

Thanks for releasing the code to public, I have a question that how did you train your model for MegaDepth? Did it train on MegaDepth or it was trained on ScanNet training set then evaluated on MegaDepth.

Thanks,
Yongqing

**Comment by Tangshitao** [comment]
It's trained with Megadepth.

**Comment by xmlyqing00** [comment]
Got it.

Thanks for your explanation.
