### ISSUE TITLE
For FeatureMatching, the QuadTreeAttention-based LoFTR is slower than the original LoFTR

### ISSUE THREAD

**Issue by KaneKun** [Tangshitao/QuadTreeAttention#4]
Hi, I find this paper very inspiring and interesting. Really appreciate the code and paper.

After testing the code on the Feature Matching task, I find it achieves better performance than the original LoFTR. But it runs a bit slower than the original LoFTR. For example, on my machine, for the same input pair of images, it runs ~0.380 s, while the original LoFTR runs ~0.27 s.

I am wondering if this is expected, or is it possibly due to my improper compilation of the QuadTreeAttention, or for some other reasons?

Thanks a lot for your help.

**Comment by Tangshitao** [comment]
That's expected. We don't optimize our cuda codes. You can refer to the appendix of the paper.
