### ISSUE TITLE
error: command '/usr/bin/gcc' failed with exit code 1 

### ISSUE THREAD

**Issue by Linyh1999** [Tangshitao/QuadTreeAttention#8]
![image](https://user-images.githubusercontent.com/101108289/169515689-f08e9ae4-2d44-4cf0-a481-3fe5125bcb4b.png)

run  python setup.py install but got  error: command '/usr/bin/gcc' failed with exit code 1

**Comment by Tangshitao** [comment]
This is not the actual error messages. Please locate real error messages.

**Comment by Linyh1999** [comment]
Thanks for your reply!
![image](https://user-images.githubusercontent.com/101108289/169630485-488dabcc-9219-4ba8-92fc-eaa17d7d6068.png)
There are a lot of warnings during installation, and only find this error. I don't know if this is real error messages.

**Comment by Tangshitao** [comment]
Which cuda version and pytorch version do you use? Please user Pytorch 1.8 and cuda 11.

**Comment by Linyh1999** [comment]
Thanks! 
It works！

**Comment by hmarichal93** [comment]
Hi,
I had some issues trying to compile it. As mantioned above, tt works using pytorch 1.8 and cuda 11. I follow the below steps:
OS (ubuntu 22.04 lts)
NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7 
cuda-toolkit 11.7

##python environment
**conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=11.1 -c pytorch -c conda-forge**

For some reason above packages depend on ffmepg=4.3 and conda url is forbidden, so installation fails. Forcing ffmepg installation with link **$conda install -n torch -c conda-forge ffmpeg=4.3** fix issue.
